
name: ETL Wheater

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build --build-arg WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} -t etl-wather .
      - name: Run ETL
        run: docker run etl-wather
